/**
 * Service-worker update scheduling.
 *
 * The worker itself is generated by vite-plugin-pwa (Workbox) and registered
 * once, from src/main.tsx. `registerType: 'autoUpdate'` means a new worker
 * takes over as soon as the browser notices it — but the browser only looks
 * on navigation, so a long-lived installed session can sit on an old build
 * for days. This adds a periodic check so a fresh deploy is discovered
 * without any "new version available" prompt.
 */

/** How often to ask the browser to re-check the worker script. */
export const UPDATE_CHECK_INTERVAL_MS = 60 * 60 * 1000;

export interface UpdatableRegistration {
  update: () => unknown;
}

/**
 * Re-check for a new worker on an interval, and once more whenever the tab
 * comes back to the foreground. Returns a function that stops checking.
 */
export const schedulePeriodicUpdate = (
  registration: UpdatableRegistration | undefined,
  intervalMs: number = UPDATE_CHECK_INTERVAL_MS
): (() => void) => {
  if (!registration || typeof registration.update !== "function") {
    return () => {};
  }

  const check = () => {
    try {
      registration.update();
    } catch {
      /* Offline or a transient failure: the next check will retry. */
    }
  };

  const timer = setInterval(check, intervalMs);

  const onVisible = () => {
    if (document.visibilityState === "visible") check();
  };
  document.addEventListener("visibilitychange", onVisible);

  return () => {
    clearInterval(timer);
    document.removeEventListener("visibilitychange", onVisible);
  };
};
