project_id = "zkamhncwbgieifloosqn"

[functions.generate-plans]
verify_jwt = true

[functions.admin-fetch]
verify_jwt = true

[functions.get-today-workout]
verify_jwt = true

[functions.get-week-completion]
verify_jwt = true

[functions.toggle-exercise]
verify_jwt = true

[functions.update-exercise]
verify_jwt = true

[functions.generate-day-suggestions]
verify_jwt = true

[functions.get-daily-quote]
verify_jwt = true

[functions.delete-account]
verify_jwt = true