import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { resolve } from "path";

/**
 * Architecture guard: the project used to carry two service workers — a
 * hand-written public/sw.js and the Workbox one generated by vite-plugin-pwa —
 * which collided on the same output filename, plus two manifests. These
 * assertions are on source, not on a build, so they fail the moment a second
 * worker, manifest or registration is reintroduced.
 */

const root = resolve(__dirname, "../..");
const read = (relative: string) => readFileSync(resolve(root, relative), "utf8");

const exists = (relative: string): boolean => {
  try {
    read(relative);
    return true;
  } catch {
    return false;
  }
};

describe("service-worker architecture", () => {
  it("has no hand-written service worker in public/", () => {
    expect(exists("public/sw.js")).toBe(false);
    expect(exists("public/service-worker.js")).toBe(false);
  });

  it("has no second manifest in public/", () => {
    // The generated manifest would silently overwrite it in dist.
    expect(exists("public/manifest.webmanifest")).toBe(false);
    expect(exists("public/manifest.json")).toBe(false);
  });

  it("registers a worker from exactly one place", () => {
    const sources = ["src/main.tsx", "index.html"];
    const registrations = sources.filter(
      (file) =>
        /serviceWorker\.register\(/.test(read(file)) || /\bregisterSW\(/.test(read(file))
    );
    expect(registrations).toEqual(["src/main.tsx"]);
  });

  it("disables the auto-injected registration so it cannot compete", () => {
    expect(read("vite.config.ts")).toMatch(/injectRegister:\s*null/);
  });

  it("links the manifest exactly once, and not by hand in index.html", () => {
    const html = read("index.html");
    const linkTags = html.match(/<link[^>]+rel=["']manifest["'][^>]*>/g) ?? [];
    expect(linkTags).toEqual([]);
  });
});

describe("PWA configuration for GitHub Pages", () => {
  const config = read("vite.config.ts");

  it("keeps the GitHub Pages base path", () => {
    // start_url, scope and the registration URL are all derived from base.
    expect(config).toMatch(/base:\s*["']\/fitssai-coach\/["']/);
  });

  it("keeps auto-update behaviour", () => {
    expect(config).toMatch(/registerType:\s*["']autoUpdate["']/);
  });

  it("cleans up precaches from previous deploys", () => {
    expect(config).toMatch(/cleanupOutdatedCaches:\s*true/);
  });

  it("declares German manifest metadata matching the app", () => {
    expect(config).toMatch(/lang:\s*["']de["']/);
    expect(config).not.toMatch(/Your AI-powered workout/);
  });

  it("uses the same theme colour as the document meta tag", () => {
    const themeInConfig = config.match(/theme_color:\s*['"]([^'"]+)['"]/)?.[1];
    const themeInHtml = read("index.html").match(
      /<meta\s+name=["']theme-color["']\s+content=["']([^"']+)["']/
    )?.[1];
    expect(themeInConfig).toBe(themeInHtml);
  });
});
