import type { TrainingNudge } from "./eligibility";

/**
 * What this app can and cannot actually deliver.
 *
 * The honest inventory, because the copy in the settings card is written
 * against it:
 *
 *   - There is **no** push backend. No Firebase Cloud Messaging, no VAPID key,
 *     no `pushManager.subscribe`, no scheduled Function, no Cloud Scheduler.
 *     Nothing can wake this app while it is closed, and nothing here pretends
 *     otherwise.
 *   - The service worker is Workbox's, generated by vite-plugin-pwa and
 *     registered once from `src/main.tsx`. It handles precaching only; it has
 *     no `push` listener to receive anything.
 *   - What *is* real is the Notifications API in a running page. A
 *     notification can be shown while the app is open — through the service
 *     worker registration where the platform requires it (Android Chrome
 *     throws on `new Notification()`), and through the constructor otherwise.
 *
 * So this module delivers exactly one thing: a system notification raised by
 * the running app, for a nudge the user has not already been shown today.
 * Everything it stores is per-device local state; no Firestore collection was
 * added for it, because a "which nudge did this browser already show" record
 * describes the browser and nothing else.
 */

/** The browser's answer about system notifications, as a single value. */
export type NotificationChannelState =
  /** The API does not exist here (older browser, non-secure context, SSR). */
  | "unsupported"
  /** Supported, never asked. Nothing is shown until the user asks for it. */
  | "default"
  | "granted"
  | "denied";

/** One device's memory of what it already showed and what was dismissed. */
export interface NudgeRecord {
  /** nudge key → `YYYY-MM-DD` it was delivered for. */
  delivered: Record<string, string>;
  /** nudge key → `YYYY-MM-DD` it was dismissed for. */
  dismissed: Record<string, string>;
}

export const NUDGE_RECORD_STORAGE_KEY = "fitssai.nudges.v1";

export const emptyNudgeRecord = (): NudgeRecord => ({ delivered: {}, dismissed: {} });

/** True only where the Notifications API is actually present. */
export const isBrowserNotificationSupported = (): boolean =>
  typeof window !== "undefined" && typeof window.Notification === "function";

/**
 * The current state, read fresh every time.
 *
 * Never cached: the user can revoke permission in browser settings without
 * telling the app, and a remembered "granted" would turn into a fake enabled
 * switch — the exact untruth this feature is not allowed to ship.
 */
export const readNotificationChannelState = (): NotificationChannelState => {
  if (!isBrowserNotificationSupported()) return "unsupported";
  const permission = window.Notification.permission;
  return permission === "granted" || permission === "denied" ? permission : "default";
};

/**
 * Ask for permission — only ever from an explicit user action.
 *
 * There is no call to this on mount, on navigation or on render anywhere in
 * the app; the only caller is the button in the settings card. A browser that
 * has already denied is not asked again (it would not prompt anyway), so a
 * refusal stays a refusal instead of becoming a recurring dialog.
 */
export const requestNotificationPermission = async (): Promise<NotificationChannelState> => {
  const current = readNotificationChannelState();
  if (current !== "default") return current;

  try {
    const result = await window.Notification.requestPermission();
    return result === "granted" || result === "denied" ? result : "default";
  } catch {
    /* Some browsers reject the legacy callback form; treat it as unanswered. */
    return readNotificationChannelState();
  }
};

const safeRead = (): string | null => {
  try {
    return localStorage.getItem(NUDGE_RECORD_STORAGE_KEY);
  } catch {
    /* Private mode or blocked storage: behave as if nothing was remembered. */
    return null;
  }
};

const safeWrite = (record: NudgeRecord): void => {
  try {
    localStorage.setItem(NUDGE_RECORD_STORAGE_KEY, JSON.stringify(record));
  } catch {
    /* Storage full or blocked. The nudge still shows; it just repeats later. */
  }
};

const readEntries = (value: unknown): Record<string, string> => {
  if (!value || typeof value !== "object" || Array.isArray(value)) return {};
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>).filter(
      ([, day]) => typeof day === "string"
    )
  ) as Record<string, string>;
};

/** The stored record, or an empty one for anything unreadable. */
export const readNudgeRecord = (): NudgeRecord => {
  const raw = safeRead();
  if (!raw) return emptyNudgeRecord();
  try {
    const parsed = JSON.parse(raw) as Partial<NudgeRecord> | null;
    return {
      delivered: readEntries(parsed?.delivered),
      dismissed: readEntries(parsed?.dismissed),
    };
  } catch {
    return emptyNudgeRecord();
  }
};

/**
 * Drop everything from before `today`.
 *
 * Only today can be nudged, so a past day's entry can never suppress anything
 * again — keeping it would grow the record without end. Dates are
 * `YYYY-MM-DD`, so a lexicographic comparison is a chronological one.
 */
export const pruneNudgeRecord = (record: NudgeRecord, today: string): NudgeRecord => {
  const keep = (entries: Record<string, string>): Record<string, string> =>
    Object.fromEntries(Object.entries(entries).filter(([, day]) => day >= today));
  return { delivered: keep(record.delivered), dismissed: keep(record.dismissed) };
};

const withEntry = (
  record: NudgeRecord,
  field: keyof NudgeRecord,
  key: string,
  day: string
): NudgeRecord => {
  const pruned = pruneNudgeRecord(record, day);
  return { ...pruned, [field]: { ...pruned[field], [key]: day } };
};

/** Remember that this exact nudge was already shown for this training day. */
export const markNudgeDelivered = (record: NudgeRecord, key: string, day: string): NudgeRecord =>
  withEntry(record, "delivered", key, day);

/** Remember that the user closed this nudge; it stays closed for the day. */
export const markNudgeDismissed = (record: NudgeRecord, key: string, day: string): NudgeRecord =>
  withEntry(record, "dismissed", key, day);

export const isNudgeDelivered = (record: NudgeRecord, key: string): boolean =>
  Object.prototype.hasOwnProperty.call(record.delivered, key);

export const isNudgeDismissed = (record: NudgeRecord, key: string): boolean =>
  Object.prototype.hasOwnProperty.call(record.dismissed, key);

/** Read, update and persist in one step, returning the new record. */
export const persistNudgeRecord = (record: NudgeRecord): NudgeRecord => {
  safeWrite(record);
  return record;
};

/** The bit of a service-worker registration this module needs. */
interface NotifyingRegistration {
  showNotification: (title: string, options?: NotificationOptions) => Promise<void> | void;
}

export interface BrowserNudgeDeps {
  /** Overridden in tests; production resolves the registered Workbox worker. */
  getRegistration?: () => Promise<NotifyingRegistration | null>;
  /** Overridden in tests; production uses the Notification constructor. */
  createNotification?: (title: string, options: NotificationOptions) => void;
}

const defaultRegistration = async (): Promise<NotifyingRegistration | null> => {
  if (typeof navigator === "undefined" || !navigator.serviceWorker) return null;
  try {
    const registration = await navigator.serviceWorker.getRegistration();
    return registration && typeof registration.showNotification === "function"
      ? (registration as unknown as NotifyingRegistration)
      : null;
  } catch {
    return null;
  }
};

/**
 * Show one nudge as a system notification, if the browser truly can.
 *
 * The service-worker registration is tried first because on Android Chrome the
 * `Notification` constructor throws outright, and the app already registers
 * exactly one worker. The constructor is the desktop fallback. A `false`
 * return means nothing was shown — the in-app card is what the user sees
 * then, and it needs no permission at all.
 */
export const showBrowserNudge = async (
  nudge: TrainingNudge,
  deps: BrowserNudgeDeps = {}
): Promise<boolean> => {
  if (readNotificationChannelState() !== "granted") return false;

  const options: NotificationOptions = {
    body: nudge.body,
    /* Same tag per training day: a re-show replaces, never stacks. */
    tag: nudge.key,
    icon: "/fitssai-coach/icons/fitssai-192.png",
    badge: "/fitssai-coach/icons/fitssai-192.png",
    silent: true,
  };

  const getRegistration = deps.getRegistration ?? defaultRegistration;
  try {
    const registration = await getRegistration();
    if (registration) {
      await registration.showNotification(nudge.title, options);
      return true;
    }
  } catch {
    /* Fall through to the constructor below. */
  }

  try {
    const create =
      deps.createNotification ??
      ((title: string, opts: NotificationOptions) => {
        new window.Notification(title, opts);
      });
    create(nudge.title, options);
    return true;
  } catch {
    return false;
  }
};
