// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkamhncwbgieifloosqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprYW1obmN3YmdpZWlmbG9vc3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTE2NDMsImV4cCI6MjA3MTcyNzY0M30.UMUTKlz_Xb85cBLsKD2L79F_garrd-1xBDwP_Z-SlXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});